### ISSUE TITLE
Error Generando planillas

### ISSUE THREAD

**Issue by arivasvera** [leninmhs/komunal#1]
Hola, estoy probando tu app y al intentar generar una planilla familiar, esto me aparece en la terminal

``` sh
Traceback (most recent call last):
  File "inicial.py", line 157, in generarPlanillaFamilia
    pdf_x_familia = QtGui.QFileDialog.getSaveFileName(self, "Guardar Planilla Komunal (*.pdf)", QtCore.QDir.homePath() + "/familia-" + str(self.ui.tableWidget.item(self.ui.tableWidget.currentRow(), 1).text()) + ".pdf", "Documento PDF (*.pdf)")
AttributeError: 'NoneType' object has no attribute 'text'
```

me ayudas?

**Comment by leninmhs** [comment]
Saludo Andres, ese error es que tienes que seleccionar un registro de la familia en el grid y luego si clickear el boton de generar la planilla. Ahora bien probando si me dio un error distinto que no existia cuando publique el codigo, actualiza el proyecto que subi los cambios y escribi algo minimo al respecto aqui: https://leninmhs.wordpress.com/2015/07/31/solucion-a-error-de-decode-en-combinacion-python-qt-pyqt-reportlab-attributeerror-qstring-object-has-no-attribute-decode/

Saludos!
